### ISSUE TITLE
用户首次进入是否可以增加提醒信息

### ISSUE THREAD

**Issue by Pingozhu** [gptlink/gptlink-deploy#2]
目前新用户通过邀请过来后，首页只有“开始提问吧~”这个提示语，这对于首次使用产品的用户还是比较无从下手的，是否可以自定义提示语，或者一个弹窗信息？期待你们的产品升级，谢谢

**Comment by 0daynick** [comment]
功能isuse提交到主仓库中，这里接收的是部署相关的问题
