### ISSUE TITLE
部署完后台访问提示：服务器错误

### ISSUE THREAD

**Issue by wclk** [gptlink/gptlink-deploy#4]
部分配置：#################  基础配置 ###################
# All Networks driver
NETWORKS_DRIVER=bridge
# All volumes driver
VOLUMES_DRIVER=local
# TIMEZONE
TIMEZONE=UTC
# 数据储存目录
DATA_PATH=./data
# 外网访问端口
GPTLINK_PORT=811
GPTLINK_SSL_PORT=444
# 使用的gptlink的镜像版本，如需使用指定版本，可自行指定
GPTLINK_VERSION=latest

部分日志：
[2023-07-26 23:48:56] default.INFO: exception {"req":[],"url":"GET http://127.0.0.1:9503/config/basic-info?","message":"Connection refused[268] in /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php","trace":"#0 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(268): Redis->connect()
#1 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(117): Hyperf\\Redis\\RedisConnection->createRedis()
#2 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(71): Hyperf\\Redis\\RedisConnection->reconnect()
#3 /app/gptserver/vendor/hyperf/redis/src/Pool/RedisPool.php(58): Hyperf\\Redis\\RedisConnection->__construct()
#4 /app/gptserver/vendor/hyperf/pool/src/Pool.php(167): Hyperf\\Redis\\Pool\\RedisPool->createConnection()
#5 /app/gptserver/vendor/hyperf/pool/src/Pool.php(60): Hyperf\\Pool\\Pool->getConnection()
#6 /app/gptserver/vendor/hyperf/redis/src/Redis.php(98): Hyperf\\Pool\\Pool->get()
#7 /app/gptserver/vendor/hyperf/redis/src/Redis.php(44): Hyperf\\Redis\\Redis->getConnection()
#8 /app/gptserver/vendor/hyperf/cache/src/Driver/RedisDriver.php(33): Hyperf\\Redis\\Redis->__call()
#9 /app/gptserver/vendor/hyperf/cache/src/Cache.php(27): Hyperf\\Cache\\Driver\\RedisDriver->get()
#10 /app/gptserver/vendor/hyperf/cache/src/Cache.php(32): Hyperf\\Cache\\Cache->__call()
#11 /app/gptserver/app/Model/Repository/ConfigTrait.php(63): Hyperf\\Cache\\Cache->get()
#12 /app/gptserver/runtime/container/proxy/App_Http_Control_Web_ConfigController.proxy.php(36): App\\Model\\Config::toDto()
#13 /app/gptserver/vendor/hyperf/http-server/src/CoreMiddleware.php(161): App\\Http\\Control\\Web\\ConfigController->getBasicInfo()
#14 /app/gptserver/vendor/hyperf/http-server/src/CoreMiddleware.php(113): Hyperf\\HttpServer\\CoreMiddleware->handleFound()
#15 /app/gptserver/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(64): Hyperf\\HttpServer\\CoreMiddleware->process()
#16 /app/gptserver/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\\Dispatcher\\AbstractRequestHandler->handleRequest()
#17 /app/gptserver/vendor/hyperf/validation/src/Middleware/ValidationMiddleware.php(83): Hyperf\\Dispatcher\\HttpRequestHandler->handle()
#18 /app/gptserver/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(64): Hyperf\\Validation\\Middleware\\ValidationMiddleware->process()
#19 /app/gptserver/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\\Dispatcher\\AbstractRequestHandler->handleRequest()
#20 /app/gptserver/vendor/cblink/hyperf-helper/src/Middleware/CorsMiddleware.php(27): Hyperf\\Dispatcher\\HttpRequestHandler->handle()
#21 /app/gptserver/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(64): Cblink\\HyperfExt\\Middleware\\CorsMiddleware->process()
#22 /app/gptserver/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\\Dispatcher\\AbstractRequestHandler->handleRequest()
#23 /app/gptserver/vendor/hyperf/dispatcher/src/HttpDispatcher.php(40): Hyperf\\Dispatcher\\HttpRequestHandler->handle()
#24 /app/gptserver/vendor/hyperf/http-server/src/Server.php(117): Hyperf\\Dispatcher\\HttpDispatcher->dispatch()
#25 {main}"} []

**Comment by fenglindubu** [comment]
我也是的：
[ERROR] RedisException: DNS Lookup resolve failed in /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php:268
Stack trace:
#0 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(268): Redis->connect()
#1 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(117): Hyperf\Redis\RedisConnection->createRedis()
#2 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(71): Hyperf\Redis\RedisConnection->reconnect()
#3 /app/gptserver/vendor/hyperf/redis/src/Pool/RedisPool.php(58): Hyperf\Redis\RedisConnection->__construct()
#4 /app/gptserver/vendor/hyperf/pool/src/Pool.php(167): Hyperf\Redis\Pool\RedisPool->createConnection()
#5 /app/gptserver/vendor/hyperf/pool/src/Pool.php(60): Hyperf\Pool\Pool->getConnection()
#6 /app/gptserver/vendor/hyperf/redis/src/Redis.php(98): Hyperf\Pool\Pool->get()
#7 /app/gptserver/vendor/hyperf/redis/src/Redis.php(44): Hyperf\Redis\Redis->getConnection()
#8 /app/gptserver/vendor/hyperf/redis/src/RedisProxy.php(32): Hyperf\Redis\Redis->__call()
#9 /app/gptserver/vendor/hyperf/async-queue/src/Driver/RedisDriver.php(193): Hyperf\Redis\RedisProxy->__call()
#10 /app/gptserver/vendor/hyperf/async-queue/src/Driver/RedisDriver.php(85): Hyperf\AsyncQueue\Driver\RedisDriver->move()
#11 /app/gptserver/vendor/hyperf/async-queue/src/Driver/Driver.php(86): Hyperf\AsyncQueue\Driver\RedisDriver->pop()
#12 /app/gptserver/vendor/hyperf/async-queue/src/Process/ConsumerProcess.php(57): Hyperf\AsyncQueue\Driver\Driver->consume()
#13 /app/gptserver/vendor/hyperf/process/src/AbstractProcess.php(134): Hyperf\AsyncQueue\Process\ConsumerProcess->handle()
#14 {main}

**Comment by 0daynick** [comment]
确保 redis 服务正常，地址与端口配置正确，并且在启动完成后再启动gptlink容器
